-- MySQL Script generated by MySQL Workbench
-- 11/09/17 09:49:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trainningpro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trainningpro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trainningpro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `trainningpro` ;

-- -----------------------------------------------------
-- Table `trainningpro`.`khoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`khoa` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`khoa` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(45) NOT NULL,
  `giao_vu_khoa_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`giang_vien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`giang_vien` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`giang_vien` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(45) NOT NULL,
  `ngay_sinh` DATE NOT NULL,
  `gioi_tinh` TINYINT(1) UNSIGNED NOT NULL,
  `email` VARCHAR(45) NULL,
  `so_dien_thoai` VARCHAR(20) NULL DEFAULT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `hoc_vi` VARCHAR(45) NOT NULL,
  `avatar` NVARCHAR(100) NULL DEFAULT NULL,
  `khoa_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `khoa_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_lecturers_faculties1_idx` (`khoa_id` ASC),
  CONSTRAINT `fk_lecturers_faculties1`
    FOREIGN KEY (`khoa_id`)
    REFERENCES `trainningpro`.`khoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`khoi_kien_thuc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`khoi_kien_thuc` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`khoi_kien_thuc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`hoc_phan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`hoc_phan` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`hoc_phan` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `vi_name` VARCHAR(45) NOT NULL,
  `en_name` TEXT NULL,
  `ma_hoc_phan` VARCHAR(45) NULL,
  `loai_hoc_phan` VARCHAR(45) NULL,
  `khoi_kien_thuc_id` INT NOT NULL,
  `so_tin_chi` INT NULL,
  PRIMARY KEY (`id`, `khoi_kien_thuc_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_hoc_phan_khoi_kien_thuc1_idx` (`khoi_kien_thuc_id` ASC),
  CONSTRAINT `fk_hoc_phan_khoi_kien_thuc1`
    FOREIGN KEY (`khoi_kien_thuc_id`)
    REFERENCES `trainningpro`.`khoi_kien_thuc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `trainningpro`.`de_cuong_hoc_phan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`de_cuong_hoc_phan` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`de_cuong_hoc_phan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `giang_vien_id` INT UNSIGNED NOT NULL,
  `giang_vien_ass_id` INT(10) UNSIGNED NOT NULL,
  `hoc_phan_id` INT(10) UNSIGNED NOT NULL,
  `mo_ta` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `giang_vien_id`),
  INDEX `fk_subject_outlines_lecturers1_idx` (`giang_vien_id` ASC),
  INDEX `fk_de_cuong_chi_tiet_giang_vien1_idx` (`giang_vien_ass_id` ASC),
  INDEX `fk_de_cuong_chi_tiet_hoc_phan1_idx` (`hoc_phan_id` ASC),  
  CONSTRAINT `fk_subject_outlines_lecturers1`
    FOREIGN KEY (`giang_vien_id`)
    REFERENCES `trainningpro`.`giang_vien` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_de_cuong_chi_tiet_giang_vien1`
    FOREIGN KEY (`giang_vien_ass_id`)
    REFERENCES `trainningpro`.`giang_vien` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_hoc_phan_de_cuong_chi_tiet1`
    FOREIGN KEY (`hoc_phan_id`)
    REFERENCES `trainningpro`.`hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `trainningpro`.`nien_khoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`nien_khoa` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`nien_khoa` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(45) NULL,
  `ctdt_mac_dinh` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`hoc_ky`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`hoc_ky` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`hoc_ky` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`loai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`loai` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`loai` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`chuong_trinh_dao_tao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`chuong_trinh_dao_tao` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`chuong_trinh_dao_tao` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nien_khoa_id` INT(10) UNSIGNED NOT NULL,
  `hoc_ki_id` INT UNSIGNED NOT NULL,
  `khoa_id` INT(10) UNSIGNED NOT NULL,
  `loai_id` INT UNSIGNED NOT NULL,
  `ten` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `loai_id`, `khoa_id`, `nien_khoa_id`, `hoc_ki_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_education_program_NienKhoa1_idx` (`nien_khoa_id` ASC),
  INDEX `fk_education_program_semesters1_idx` (`hoc_ki_id` ASC),
  INDEX `fk_education_program_faculties1_idx` (`khoa_id` ASC),
  INDEX `fk_education_program_category1_idx` (`loai_id` ASC),
  CONSTRAINT `fk_education_program_NienKhoa1`
    FOREIGN KEY (`nien_khoa_id`)
    REFERENCES `trainningpro`.`nien_khoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_program_semesters1`
    FOREIGN KEY (`hoc_ki_id`)
    REFERENCES `trainningpro`.`hoc_ky` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_program_faculties1`
    FOREIGN KEY (`khoa_id`)
    REFERENCES `trainningpro`.`khoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_program_category1`
    FOREIGN KEY (`loai_id`)
    REFERENCES `trainningpro`.`loai` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`hoc_phan_ctdt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`hoc_phan_ctdt` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`hoc_phan_ctdt` (
  `chuong_trinh_dao_tao_id` INT(10) UNSIGNED NOT NULL,
  `hoc_phan_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`chuong_trinh_dao_tao_id`, `hoc_phan_id`),
  INDEX `fk_subjects_has_education_program_education_program1_idx` (`chuong_trinh_dao_tao_id` ASC),
  INDEX `fk_hoc_phan_ctdt_hoc_phan1_idx` (`hoc_phan_id` ASC),
  CONSTRAINT `fk_subjects_has_education_program_education_program1`
    FOREIGN KEY (`chuong_trinh_dao_tao_id`)
    REFERENCES `trainningpro`.`chuong_trinh_dao_tao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hoc_phan_ctdt_hoc_phan1`
    FOREIGN KEY (`hoc_phan_id`)
    REFERENCES `trainningpro`.`hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`tai_lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`tai_lieu` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`tai_lieu` (
  `id` INT NOT NULL,
  `tieu_de` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`loai_hoc_lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`loai_hoc_lieu` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`loai_hoc_lieu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten_loai` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`nguon_hoc_lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`nguon_hoc_lieu` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`nguon_hoc_lieu` (
  `id` INT NOT NULL,
  `ten_hoc_lieu` VARCHAR(150) NOT NULL,
  `de_cuong_chi_tiet_id` INT NOT NULL,
  `loai_hoc_lieu_id` INT NOT NULL,
  PRIMARY KEY (`id`, `de_cuong_chi_tiet_id`),
  INDEX `fk_nguon_hoc_lieu_de_cuong_chi_tiet1_idx` (`de_cuong_chi_tiet_id` ASC),
  INDEX `fk_nguon_hoc_lieu_loai_hoc_lieu1_idx` (`loai_hoc_lieu_id` ASC),
  CONSTRAINT `fk_nguon_hoc_lieu_de_cuong_chi_tiet1`
    FOREIGN KEY (`de_cuong_chi_tiet_id`)
    REFERENCES `trainningpro`.`de_cuong_hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nguon_hoc_lieu_loai_hoc_lieu1`
    FOREIGN KEY (`loai_hoc_lieu_id`)
    REFERENCES `trainningpro`.`loai_hoc_lieu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`chuan_dau_ra_ctdt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`chuan_dau_ra_ctdt` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`chuan_dau_ra_ctdt` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `ten_cdr` VARCHAR(45) NOT NULL,
  `mota` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`muc_tieu_hoc_phan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`muc_tieu_hoc_phan` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`muc_tieu_hoc_phan` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `mota` VARCHAR(45) NOT NULL,
  `trinh_do_nang_luc` VARCHAR(10) NULL,
  `de_cuong_chi_tiet_id` INT NOT NULL,
  `ten` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `de_cuong_chi_tiet_id`),
  INDEX `fk_muc_tieu_hoc_phan_de_cuong_chi_tiet1_idx` (`de_cuong_chi_tiet_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_muc_tieu_hoc_phan_de_cuong_chi_tiet1`
    FOREIGN KEY (`de_cuong_chi_tiet_id`)
    REFERENCES `trainningpro`.`de_cuong_hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`muc_tieu_dap_ung_ctdt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`muc_tieu_dap_ung_ctdt` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`muc_tieu_dap_ung_ctdt` (
  `muc_tieu_hoc_phan_id` INT(10) NOT NULL,
  `chuan_dau_ra_ctdt_id` INT NOT NULL,
  PRIMARY KEY (`muc_tieu_hoc_phan_id`, `chuan_dau_ra_ctdt_id`),
  INDEX `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_ctdt_chuan_dau_ra_ctd_idx` (`chuan_dau_ra_ctdt_id` ASC),
  INDEX `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_ctdt_muc_tieu_hoc_pha_idx` (`muc_tieu_hoc_phan_id` ASC),
  CONSTRAINT `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_ctdt_muc_tieu_hoc_phan1`
    FOREIGN KEY (`muc_tieu_hoc_phan_id`)
    REFERENCES `trainningpro`.`muc_tieu_hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_ctdt_chuan_dau_ra_ctdt1`
    FOREIGN KEY (`chuan_dau_ra_ctdt_id`)
    REFERENCES `trainningpro`.`chuan_dau_ra_ctdt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`chuan_dau_ra_hoc_phan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`chuan_dau_ra_hoc_phan` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`chuan_dau_ra_hoc_phan` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `mota` VARCHAR(100) NOT NULL,
  `muc_do_giang_day` VARCHAR(10) NULL,
  `ten` VARCHAR(45) NULL,
  `de_cuong_chi_tiet_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chuan_dau_ra_hoc_phan_de_cuong_chi_tiet1_idx` (`de_cuong_chi_tiet_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_chuan_dau_ra_hoc_phan_de_cuong_chi_tiet1`
    FOREIGN KEY (`de_cuong_chi_tiet_id`)
    REFERENCES `trainningpro`.`de_cuong_hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainningpro`.`muc_tieu_hoc_phan_has_chuan_dau_ra_hoc_phan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trainningpro`.`muc_tieu_hoc_phan_has_chuan_dau_ra_hoc_phan` ;

CREATE TABLE IF NOT EXISTS `trainningpro`.`muc_tieu_hoc_phan_has_chuan_dau_ra_hoc_phan` (
  `muc_tieu_hoc_phan_id` INT(10) NOT NULL,
  `chuan_dau_ra_hoc_phan_id` INT(10) NOT NULL,
  PRIMARY KEY (`muc_tieu_hoc_phan_id`, `chuan_dau_ra_hoc_phan_id`),
  INDEX `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_hoc_phan_chuan_dau_ra_idx` (`chuan_dau_ra_hoc_phan_id` ASC),
  INDEX `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_hoc_phan_muc_tieu_hoc_idx` (`muc_tieu_hoc_phan_id` ASC),
  CONSTRAINT `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_hoc_phan_muc_tieu_hoc_p1`
    FOREIGN KEY (`muc_tieu_hoc_phan_id`)
    REFERENCES `trainningpro`.`muc_tieu_hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_muc_tieu_hoc_phan_has_chuan_dau_ra_hoc_phan_chuan_dau_ra_h1`
    FOREIGN KEY (`chuan_dau_ra_hoc_phan_id`)
    REFERENCES `trainningpro`.`chuan_dau_ra_hoc_phan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use trainningpro;
-- khoa
INSERT INTO khoa (ten, giao_vu_khoa_id) VALUES
('CN Nhiet - Dien lanh', 5), ('Co khi', 2), ('Co khi Giao thong', 3), ('Cong nghe thong tin', 4), ('Dien', 6),
('Dien tu Vien thong', 7), ('Hoa', 8), ('Kien truc', 9), ('Moi truong', 10), ('Quan ly Du an', 11), ('Su pham Ky thuat', 12),
('XD - Cau duong', 13), ('XD Dan dung - Cong nghiep', 14), ('XD Thuy loi - Thuy dien', 15)
;
-- Giang Vien
INSERT INTO giang_vien (ten, ngay_sinh, gioi_tinh, email, so_dien_thoai, username, password, hoc_vi, avatar, khoa_id) VALUES 
('Le Thi My Hanh', str_to_date('040709','%m%d%Y'), 0, 'ltmhanh@dut.udn.vn', '0123456789', 'ltmhanh', 'secret', 'Tien Sy', null, 4),
('Mai Van Ha', str_to_date('040709','%m%d%Y'), 1, 'mvha@dut.udn.vn', '0123456789', 'mvha', 'secret', 'Thac Sy', null, 4),
('Nguyen Van Nguyen', str_to_date('040709','%m%d%Y'), 1, 'nvnguyen@dut.udn.vn', '0123456789', 'nvnguyen', 'secret', 'Thac Sy', null, 4),
('Dao Thi My Hanh', str_to_date('040709','%m%d%Y'), 0, 'dtmhanh@dut.udn.vn', '0123456789', 'dtmhanh', 'secret', 'Tien Sy', null, 4),
('Nguyen Van A', str_to_date('040709','%m%d%Y'), 1, 'nva@dut.udn.vn', '0123456789', 'nguyenvana', 'secret', 'Tien Sy', null, 5),
('Nguyen Thi B', str_to_date('040709','%m%d%Y'), 0, 'ntb@dut.udn.vn', '0123456789', 'nguyenthib', 'secret', 'PGS', null, 4),
('Le Van C', str_to_date('040709','%m%d%Y'), 1, 'lvc@dut.udn.vn', '0123456789', 'levanc', 'secret', 'Tien Sy', null, 4);
-- hoc ky
INSERT INTO hoc_ky (ten) VALUES
('Hoc ky I'), ('Hoc ky II'), ('Hoc ky III'), ('Hoc ky IV'), ('Hoc ky V'), ('Hoc ky VI'),
('Hoc ky VII'), ('Hoc ky VIII'), ('Hoc ky IX'), ('Hoc ky X');
-- khoi kien thuc
INSERT INTO khoi_kien_thuc (ten) VALUES
('Kien thuc dai cuong'), ('Kien thuc co so nganh'), ('Kien thuc chuyen nganh'), ('Kien thuc khac'), ('Hoc phan ve ky nang chung'),
('Hoc phan thuc tap/Do an tot nghiep');
-- hoc phan
INSERT INTO hoc_phan (vi_name, en_name, ma_hoc_phan, loai_hoc_phan, khoi_kien_thuc_id) VALUES
('Hinh Hoa', 'Graphics', null, 'Bat buoc', 1),
('Giai tich', 'Analytics', null, 'Bat buoc', 1),
('Ve ky thuat', null, null, 'Bat buoc', 1), 
('Tu tuong Mac Lenin', 'Mac Lenin', null, 'Bat buoc', 1),
('Nguyen ly 1', null, null, 'Bat buoc', 1),
('Nguyen ly 2', 'Analytics', null, 'Bat buoc', 1),
('Tin hoc dai cuong', 'Analytics', null, 'Bat buoc', 1),
('TH Tin hoc dai cuong', 'Analytics', null, 'Bat buoc', 1),
('Co so nganh mang', null, null, 'Bat buoc', 2),
('Cong nghe phan mem', null, null, 'Bat buoc', 2),
('Quan ly du an', null, null, 'Tu chon', 3),
('Chuyen de CNPM', null, null, 'Tu chon', 3),
('Do an CSNM', null, null, 'Bat buoc', 2),
('Do an CNPM', null, null, 'Bat buoc', 3),
('Thuc tap cong nhan', null, null, 'Bat buoc', 4),
('Thuc tap tot nghiep', null, null, 'Bat buoc', 6),
('Phap luat dai cuong', null, null, 'Bat buoc', 4);
-- chuan dau ra hoc phan
INSERT INTO chuan_dau_ra_hoc_phan (mota, muc_do_giang_day) VALUES
('Kien thuc va lap luan nganh', 'I'),
('Hieu duoc cac khai niem, phuong phap, ky thuat trong phan tich va thiet ke', 'T'),
('Co kha nang quan ly thoi gian', 'I'),
('Phat trien duoc ky nang giao tiep', 'I'),
('Ky nang, pham chat ca nhan va nghe nghiep', 'U'),
('Phat trien ky nang lam viec nhom', 'I'),
('Ky nang va pham chat giua cac ca nhan', null),
('Nang luc thuc hanh nghe nghiep', null);
-- chuan dau ra CTDT
INSERT INTO chuan_dau_ra_ctdt (ten_cdr, mota) VALUES
('CDR1', null), ('CDR2', null), ('CDR3', null), ('CDR4', null), ('CDR5', null), ('CDR6', null);

